apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-catalog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce-catalog
  template:
    metadata:
      labels:
        app: ecommerce-catalog
    spec:
      containers:
        - name: ecommerce-catalog
          image: your-image-name:tag
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-catalog
spec:
  selector:
    app: ecommerce-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
